# makefile for AV using MINGW compiler

CC=gcc
MAKE= make 
PGMS= emav/emav.exe putt/putt.exe
LIBD=lib/mgw
LIBS= $(LIBD)/libfft.a $(LIBD)/libmenu.a $(LIBD)/libtok.a \
	$(LIBD)/libutil.a $(LIBD)/libdsp.a 

build : $(LIBS) $(PGMS)

# build libs

$(LIBDIR) :
	mkdir lib 
	mkdir $(LIBDIR)
dsp/libdsp.a :
	$(MAKE) -C dsp libdsp.a
fft/libfft.a :
	$(MAKE) -C fft libfft.a
menu/libmenu.a :
	$(MAKE) -C menu libmenu.a
tok/libtok.a :
	$(MAKE) -C tok libtok.a
util/libutil.a :
	$(MAKE) -C util libutil.a

# install libs

$(LIBD)/libdsp.a : dsp/libdsp.a $(LIBDIR)
	$(MAKE) -C dsp install
$(LIBD)/libfft.a : fft/libfft.a $(LIBDIR)
	$(MAKE) -C fft install
$(LIBD)/libmenu.a : menu/libmenu.a $(LIBDIR)
	$(MAKE) -C menu install
$(LIBD)/libtok.a : tok/libtok.a lib $(LIBDIR)
	$(MAKE) -C tok install
$(LIBD)/libutil.a : util/libutil.a lib $(LIBDIR)
	$(MAKE) -C util install

# build apps

emav/emav.exe : $(LIBS)
	$(MAKE) -C emav
putt/putt.exe : $(LIBS)
	$(MAKE) -C putt

install: $(PGMS)
	$(MAKE) -C emav install
	$(MAKE) -C putt install

avsc.zip :
	rm -f avsc.zip
	zip avsc configure configure.bat
	zip avsc *.mgw *.lnx *.mac
	zip avsc dsp/*.c dsp/*.h dsp/*.asm 
	zip avsc dsp/*.mgw dsp/*.lnx dsp/*.mac
	zip avsc emav/*.asm emav/*.txt emav/*.pl
	zip avsc emav/*.c emav/*.h emav/*.bat emav/*.ini 
	zip avsc emav/*.iss emav/*.m
	zip avsc emav/*.rc emav/*.ico 
	zip avsc emav/*.mgw emav/*.lnx emav/*.mac emav/*.win
	zip avsc emav/std.lst emav/fdpswp.lst emav/4kio.lst emav/suppr.lst 
	zip avsc fft/*.c fft/*.h 
	zip avsc fft/*.mgw fft/*.lnx fft/*.mac
	zip avsc include/*.h
	zip avsc lib/dj/*.txt lib/linux/*.txt
	zip avsc menu/*.c menu/*.h 
	zip avsc menu/*.mgw menu/*.lnx menu/*.mac 
	zip avsc putt/*.c putt/*.h putt/*.bat putt/*.ini
	zip avsc putt/*.iss putt/*.m
	zip avsc putt/*.rc putt/*.ico 
	zip avsc putt/*.mgw putt/*.lnx putt/*.mac putt/*.pl
	zip avsc tok/*.c tok/*.h 
	zip avsc tok/*.mgw tok/*.lnx tok/*.mac 
	zip avsc util/*.c util/*.h 
	zip avsc util/*.mgw util/*.lnx util/*.mac 
	zip avsc VS16/*.sln VS16/*.vcxproj VS16/*.filters

zipsrc : avsc.zip

# build distributions

dist : $(PGMS) avsc.zip
	$(MAKE) -C emav dist
	$(MAKE) -C putt dist
	mv -f avsc.zip ../dist

# clean

clean:
	rm -f $(LIBDIR)/*.a
	$(MAKE) -C emav clean
	$(MAKE) -C putt clean
	$(MAKE) -C dsp clean
	$(MAKE) -C fft clean
	$(MAKE) -C menu clean
	$(MAKE) -C tok clean
	$(MAKE) -C util clean

