; emav.ini - EMAV initialization file for Indigo

[SYSTEM]
;
; Etymotic ER-10C
;
;MP_sensitivity=0.05      ; V/Pa (GAIN=0)
MP_sensitivity=0.50      ; V/Pa (GAIN=+20, Mimosa)
;MP_sensitivity=5.00      ; V/Pa (GAIN=+40)
LS1_sensitivity=2.76     ; V/Pa (sw@1V, CEL, 24-Oct-03)
LS2_sensitivity=2.96     ; V/Pa (sw@1V, CEL, 24-Oct-03)
;
; Indigo [23-Oct-03]
;
DSP=W
DSP_CODE=Indigo
AD_sensitivity=3566000  ; cnt/V
DA1_sensitivity=15000   ; cnt/V
DA2_sensitivity=15000   ; cnt/V
;
; CardDeluxe [CEL, 24-Oct-03]
;
;DSP=W
;DSP_CODE=CardDeluxe
;AD_sensitivity=856907   ; cnt/V (+4dB)
;DA1_sensitivity=6922    ; cnt/V (+4db)
;DA2_sensitivity=6548    ; cnt/V (+4dB)
;
refresh=5
hpf1=250

[PRINTER]
;port=\\nerhps01\research3c
;port=\\cellinux\Printer
port=\\neelypc\HP970CSe
label=Communication Engineering Laboratory

[TEOAE]
rate=32000
chk_swps=25
limit=1
sweeps=8
sets=128
size=512
mode=3
time1=6
time2=14
adjust=auto
Trefresh=2
FFTdB=80
FFTkHz=10
Target=80

[DPOAE]
rate=32000
size=8192
sweeps=8
limit=4
list=*.lst
thsf=*.ths
FFTdB=100
chk_swps=2
cal_swps=4
chk_atten=20
atten=20
scope=8192
sets=2
skips=1
SpecFreqRange=Auto
signal=DP+
NNSB=-5
CalibratePhase=Yes
Count=0
hpf1=250
HPF_freq=100
Level_unit=SPL

[PROBE]
FFTdB=60
FFTkHz=10
Niter=8000
Temp=25
Diacav=0.8
Max_len=9
Ncav=5
MinRes=4
Smooth=0
Dec_Len=Y

[TONE]
rate=32000
size=2048
ramp=20
frequency=1000
level=65
duration=2
repeated=1
channel=a
