# makefile - for EMAV using MINGW compiler 

CC=gcc
LIBDIR=../lib/mgw
INCDIR=../include
BINDIR=c:/usr/bin
CFLAGS = -DMGW -O2 -Wall -DANSI_C -I$(INCDIR) -fpack-struct 
LFLAGS = -L$(LIBDIR)
WINLIB = -lwinmm -lkernel32 -luser32 -lgdi32 -lcomdlg32
LIBS = -ldsp -lfft -lmenu -ltok -lutil -lm $(WINLIB) 

CFILES = emav.c savage.c naverage.c disadbuf.c \
    event.c infowind.c dofft.c teoae_w.c \
    repro.c dpoae_w.c rdwrdram.c tone_w.c file.c param.c \
    screen.c view.c wind.c  showdp.c \
    sfextr.c calfile.c probe_w.c simp.c
OFILES=emav.o savage.o naverage.o disadbuf.o \
     event.o infowind.o dofft.o teoae_w.o \
    repro.o dpoae_w.o rdwrdram.o tone_w.o file.o param.o \
    screen.o view.o wind.o showdp.o \
    sfextr.o calfile.o probe_w.o simp.o
EXEFILES=emav oba2 binmat calmat tokmat

all: $(EXEFILES)

emav : $(OFILES)
	gcc $(LFLAGS) -o emav $(OFILES) $(LIBS)

oba2 : oba2.o
	gcc $(LFLAGS) -o oba2 oba2.o -lfft -ltok -lm

binmat : binmat.o
	gcc $(LFLAGS) -o binmat binmat.o -lm

calmat : calmat.o
	gcc $(LFLAGS) -o calmat calmat.o -ltok -lm

tokmat : tokmat.o
	gcc $(LFLAGS) -o tokmat tokmat.o -ltok -lm

$(BINDIR)/emav.exe : emav
	mkdir -p $(BINDIR)
	cp emav.exe $(BINDIR)

install: $(BINDIR)/emav.exe

clean:
	rm -f *.bak *.o *.out *.pdb *.hex *.map *.log *.ncb *.opt
	rm -f *.plg *.cnt *.cv4 *.sts *.ps *~ *.mat
	rm -f $(EXEFILES) *.exe
	rm -f rf*.txt rt*.txt dx*.txt

emav.zip: $(EXEFILES)
	zip emav emav.exe emav.ico oba2.exe calmat.exe tokmat.exe
	zip emav emav.ini std.lst fdpswp.lst suppr.lst
	zip emav 93c25*.* dp*.plt 92l21*.* dp-aud.* te-aud.*

version: 
	perl version.pl

emav-setup.zip: version
	../../setup/iscc.exe emav.iss
	cp readme.win Output/_README.txt
	zip -j emav-setup Output/setup.exe Output/*.txt
	rm -rf Output

emav-mat.zip: binmat calmat tokmat
	zip emav-mat binmat.c   calmat.c   tokmat.c
	zip emav-mat binmat.m   calmat.m   tokmat.m
	zip emav-mat binmat.exe calmat.exe tokmat.exe

dist: emav.zip emav-setup.zip emav-mat.zip
	mv -f emav.zip ../../dist
	mv -f emav-setup.zip ../../dist
	mv -f emav-mat.zip ../../dist

# C file dependencies
# (makedep will replace everything after this line) 

disadbuf.o: savage.h color.h emav.h
dofft.o: savage.h color.h
dpoae_w.o: savage.h color.h emav.h screen.h version.h fk.h
emav.o: savage.h color.h version.h emav.h screen.h
event.o: savage.h color.h version.h emav.h
file.o: savage.h color.h version.h screen.h
infowind.o: savage.h color.h
naverage.o: savage.h color.h emav.h screen.h
param.o: savage.h color.h emav.h screen.h
rdwrdram.o: savage.h color.h
repro.o: savage.h
savage.o: savage.h color.h emav.h
screen.o: screen.h color.h
teoae_w.o: savage.h color.h emav.h screen.h
tone_w.o: savage.h color.h screen.h emav.h
