EMAV runs as a command-line program on macOS. EMAV utilizes native Apple Cocoa and CoreGraphics frameworks for its user interface, and CoreAudio for its soundcard functions.

EMAV installation:

The executable program file "emav" should be placed in /usr/local/bin.
The configuration file "emav.ini" should be edited to have the desired
default parameter values and placed either in a subdirectory created for
EMAV data files or in /usr/local/etc.
