; abrav.ini - ABRAV initialization file
[SYSTEM]
;
; Etymotic ER-10C
;
;MP_sensitivity=0.05      ; V/Pa (GAIN=0)
MP_sensitivity=0.50      ; V/Pa (GAIN=+20, Mimosa)
;MP_sensitivity=5.00      ; V/Pa (GAIN=+40)
;MP_sensitivity=mp_sens.txt
LS1_sensitivity=2.76     ; V/Pa (sw@1V, CEL, 24-Oct-03)
LS2_sensitivity=2.96     ; V/Pa (sw@1V, CEL, 24-Oct-03)
;
; Indigo [23-Oct-03]
;
;DSP=W
;DSP_CODE=Indigo
;AD_sensitivity=3566000  ; cnt/V
;DA1_sensitivity=15000   ; cnt/V
;DA2_sensitivity=15000   ; cnt/V
;
; CardDeluxe [CEL, 24-Oct-03]
;
DSP=W
DSP_CODE=CardDeluxe
AD_sensitivity=856907   ; cnt/V (+4dB)
DA1_sensitivity=6922    ; cnt/V (+4db)
DA2_sensitivity=6548    ; cnt/V (+4dB)
;
refresh=5

[PRINTER]
port=\\nerhps01\research3c
;port=\\cellinux\Printer
label=Communication Engineering Laboratory

[ABR]
Size=1024
Rate=32000
Sweeps=25
Sets=80
limit=1
mode=0
; stimulus=100us.stm
chk_atten=20
chk_swps=25
cal_atten=10
chk_size=1024
cal_atten=20
cal_swps=25
Target=90.0
Tolerance=3
Trefresh=5
FFTkHz=5
Filter=N
MAX_level=105
NHL_level=30
Xrange=20
Yrange=10e-3
Reject_Mode=Raw
Tone_Freq=1000
Tone_Level=60
time1=4
time2=12
F1=10
F2=1500
Nmp=9
Min_Sets=20
Wt_Av=SPRMS
EPA_AGN=100
EPA_PGN=1000
EPA_HPF=100
EPA_LPF=3000
EPA_NOTCH=Out
EPA_FLAG=0
PQM=Fmp
AQM=SNR
VR1=2
VR2=3
repr1=50
repr2=90
PQM_stop=0
OK_stop=0
List=*.lst
check_signal=0

[TONE]
rate=32000
size=2048
ramp=20
frequency=1000
level=65
duration=2
repeated=1
channel=a
