# makefile - for ABRAV using MINGW compiler

CC=gcc
LIBDIR=../lib/mgw
INCDIR=../include
BINDIR=c:/usr/bin
CFLAGS = -DMGW -O2 -Wall -DANSI_C -I$(INCDIR) -fpack-struct 
LFLAGS = -L$(LIBDIR)
WINLIB = -lwinmm -lkernel32 -luser32 -lgdi32 -lcomdlg32
LIBS = -ldsp -lfft -lmenu -ltok -lutil -lm $(WINLIB) 

CFILES = abrav.c savage.c naverage.c dcremo.c \
    disadbuf.c event.c dofft.c screen.c \
    infowind.c abr_w.c rdwrdram.c edit.c \
    tone_w.c file.c var.c epamp.c 
OFILES=abrav.o savage.o naverage.o dcremo.o \
    disadbuf.o event.o dofft.o screen.o \
    infowind.o abr_w.o rdwrdram.o edit.o \
    tone_w.o file.o var.o epamp.o 
EXEFILES=abrav

all: $(EXEFILES) 

abrav : $(OFILES)
	gcc $(LFLAGS) -o abrav $(OFILES) $(LIBS)

$(BINDIR)/abrav.exe : abrav
	mkdir -p $(BINDIR)
	cp abrav.exe $(BINDIR)

install: $(BINDIR)/abrav.exe 

clean:
	rm -f *.bak *.o *.out *.pdb *.hex *.map *.log *.ncb *.opt
	rm -f *.plg *.cnt *.cv4 *.sts abrav abrav.exe

abrav.zip: $(EXEFILES)
	zip abrav abrav.exe abrav.ini 93i14a0?.abr 

version: 
	perl version.pl

abrav-setup.zip: version
	../../setup/iscc.exe abrav.iss
	cp readme.win Output/_README.txt
	zip -j abrav-setup Output/setup.exe Output/*.txt
	rm -rf Output

zipdem: abrav.zip

setup: abrav-setup.zip

dist: abrav.zip abrav-setup.zip
	mv -f abrav.zip ../../dist
	mv -f abrav-setup.zip ../../dist

# C file dependencies
# (makedep will replace everything after this line) 

abr_w.o: savage.h color.h screen.h version.h
abrav.o: savage.h color.h screen.h version.h abrav.h
disadbuf.o: savage.h color.h
dofft.o: savage.h color.h
edit.o: savage.h color.h screen.h
event.o: color.h abrav.h
file.o: savage.h color.h screen.h version.h abrav.h
infowind.o: savage.h color.h
naverage.o: savage.h color.h screen.h version.h
rdwrdram.o: savage.h color.h
savage.o: savage.h color.h
screen.o: screen.h color.h
tone_w.o: savage.h color.h screen.h
var.o: savage.h template.h
