# makefile - for TSTDSP using MINGW compiler

CC=gcc
LIBDIR=../lib/mgw
INCDIR=../include
CFLAGS = -O2 -Wall -DANSI_C -I$(INCDIR) -fpack-struct 
LFLAGS = -L$(LIBDIR)
DSPC = dsp_none.c
DSPO = dsp_none.o
WINLIB = -lwinmm -lkernel32 -luser32 -lgdi32 -lcomdlg32
LIBS = -lfft -lmenu -ltok -lutil -lm $(WINLIB) 
#
BIN=c:/usr/bin
CFILES=tstdsp.c savage.c $(DSPC) \
    disadbuf.c event.c dofft.c screen.c \
    rdwrdram.c chkfit.c tone_w.c etc.c anafilt.c
OFILES=tstdsp.o savage.o $(DSPO) \
    disadbuf.o event.o dofft.o screen.o \
    rdwrdram.o chkfit.o tone_w.o etc.o anafilt.o

all: tstdsp

tstdsp : tstdsp.o libdsp.a
	gcc $(LFLAGS) -o tstdsp $+ $(LIBS)

# dsp.lib

libdsp.a : $(OFILES)
	ar rus libdsp.a $(OFILES)

# install

$(LIBDIR)/libdsp.a : libdsp.a
	cp libdsp.a $(LIBDIR)

$(INCDIR)/dsp.h : dsp.h
	cp dsp.h $(INCDIR)

install : $(LIBDIR)/libdsp.a $(INCDIR)/dsp.h

clean:
	rm -f *.bak *.exe *.hex *.lib *.log *.lst *.map *.obj *.out *.pdb
	rm -f *.o *.a tstdsp

# C file dependencies
# (makedep will replace everything after this line) 

calfile.o: savage.h
chkfit.o: savage.h screen.h
disadbuf.o: savage.h
dofft.o: savage.h
dsp.o: dsp.h
dsp0.o: dsp16.h
event.o:
infowind.o: savage.h
probe_w.o: savage.h screen.h
rdwrdram.o: savage.h
savage.o: savage.h screen.h
screen.o: screen.h
setatt.o: savage.h
tone_w.o: savage.h screen.h
tstdsp.o: savage.h screen.h
