# makefile - for FFT library using MINGW compiler

CC=gcc
FFT_O= fastc.o faip.o fasubs.o fsstc.o fsip.o fssubs.o unic.o
LIBDIR=../lib/mgw
INCDIR=../include

test : fmc
	fmc > fmc.txt

fmc : fmc.o libfft.a
	gcc -o fmc fmc.o libfft.a -lm

fmc.o : fmc.c

libfft.a: $(FFT_O)
	ar rus libfft.a $(FFT_O)

$(LIBDIR)/libfft.a : libfft.a
	cp libfft.a $(LIBDIR)

$(INCDIR)/fftlib.h : fftlib.h
	cp fftlib.h $(INCDIR)

install: $(LIBDIR)/libfft.a $(INCDIR)/fftlib.h

clean:
	rm -f *.o *.obj *.bak *.a *.exe fmc fmc.txt
