# makefile - for TOKEN library using MINGW compiler

CC=gcc
CFLAGS = -DMGW -O2 -Wall -DANSI_C -I$(INCDIR) -fpack-struct 
OFILES= topen.o tcreat.o tinit.o tread.o twrite.o tclose.o
LIBDIR=../lib/mgw
INCDIR=../include

libtok.a : $(OFILES)
	ar rus libtok.a $(OFILES)

# install

$(LIBDIR)/libtok.a : libtok.a
	cp  libtok.a $(LIBDIR)/libtok.a

$(INCDIR)/token.h : token.h
	cp  token.h $(INCDIR)/token.h

install : $(LIBDIR)/libtok.a $(INCDIR)/token.h

clean:
	rm -f *~ *.bak *.o *.a *.obj *.lib

# dependencies

misc.o : misc.c
topen.o : topen.c tokio.h
tcreat.o : topen.c tokio.h
tinit.o : topen.c tokio.h
tread.o : tread.c tokio.h
twrite.o : twrite.c tokio.h
tclose.o : tclose.c tokio.h
