# makefile - for PUTT using MINGW compiler

CC=gcc
LIBDIR=../lib/mgw
INCDIR=../include
BINDIR=c:/usr/bin
CFLAGS = -DMGW -O2 -Wall -DANSI_C -I$(INCDIR) -fpack-struct 
LFLAGS = -L$(LIBDIR)
WINLIB = -lwinmm -lkernel32 -luser32 -lgdi32 -lcomdlg32
LIBS = -ldsp -lfft -lmenu -ltok -lutil -lm $(WINLIB) 

CFILES=putt.c savage.c naverage.c \
    setatt.c disadbuf.c event.c dofft.c screen.c calfile.c \
    infowind.c chkfit.c calibr.c rdwrdram.c button.c \
    tone_w.c file.c hear_w.c mlmeer.c probe_w.c simp.c
OFILES=putt.o savage.o naverage.o \
    setatt.o disadbuf.o event.o dofft.o screen.o calfile.o \
    infowind.o chkfit.o calibr.o rdwrdram.o button.o \
    tone_w.o file.o hear_w.o mlmeer.o probe_w.o simp.o
EXEFILES=putt

all: $(EXEFILES)

putt : $(OFILES)
	gcc $(LFLAGS) -o putt $(OFILES) $(LIBS)

zipdem: putt
	zip putt putt.exe putt.ini swp.ils probe.fnf
	zip -j putt data1996/96*.th* data2008/08*.th*

version: 
	perl version.pl

setup: version
	../../setup/iscc.exe putt.iss
	cp readme.win Output/_README.txt
	zip -j putt-setup Output/setup.exe Output/*.txt
	rm -rf Output

dist: zipdem setup
	mv -f putt.zip ../../dist
	mv -f putt-setup.zip ../../dist

$(BINDIR)/putt.exe : putt.exe
	mkdir -p $(BINDIR)
	cp -f putt.exe $(BINDIR)/putt.exe

install: $(BINDIR)/putt.exe

clean:
	rm -f *.bak *.o *.out *.pdb *.hex *.map *.log *.ncb *.opt
	rm -f *.plg *.cnt *.cv4 *.sts *~ putt putt.exe

# C file dependencies
# (makedep will replace everything after this line) 

calfile.o: savage.h putt.h
calibr.o: savage.h color.h screen.h putt.h
chkfit.o: savage.h color.h screen.h putt.h
disadbuf.o: savage.h color.h
dofft.o: savage.h color.h putt.h
event.o: screen.h color.h version.h
file.o: savage.h color.h screen.h putt.h
hear_w.o: savage.h color.h screen.h version.h putt.h
hf.o: putt.h
infowind.o: savage.h color.h
naverage.o: savage.h color.h screen.h putt.h
probe_w.o: savage.h color.h screen.h putt.h
putt.o: savage.h color.h screen.h version.h putt.h
rdwrdram.o: savage.h color.h putt.h
savage.o: savage.h color.h screen.h putt.h
screen.o: screen.h color.h
setatt.o: savage.h
tone_w.o: savage.h color.h screen.h putt.h
