; putt.ini - PUTT initialization file

[SYSTEM]
;
; Etymotic ER-10C
;
;MP_sensitivity=0.05      ; V/Pa (GAIN=0)
MP_sensitivity=0.50      ; V/Pa (GAIN=+20, Mimosa)
;MP_sensitivity=5.00      ; V/Pa (GAIN=+40)
LS1_sensitivity=2.76     ; V/Pa (sw@1V, CEL, 24-Oct-03)
LS2_sensitivity=2.96     ; V/Pa (sw@1V, CEL, 24-Oct-03)
;
; Indigo [23-Oct-03]
;
;DSP=W
;DSP_CODE=Indigo io virtual 1/2 ASIO
;AD_sensitivity=3566000  ; cnt/V
;DA1_sensitivity=15000   ; cnt/V
;DA2_sensitivity=15000   ; cnt/V
;
; CardDeluxe [CEL, 24-Oct-03]
;
;DSP=W
;DSP_CODE=CardDeluxe
;AD_sensitivity=856907   ; cnt/V (+4dB)
;DA1_sensitivity=6922    ; cnt/V (+4db)
;DA2_sensitivity=6548    ; cnt/V (+4dB)
;
refresh=5

[PRINTER]
port=\\nerhps01\research3c
;port=\\cellinux\Printer
label=Communication Engineering Laboratory

[HEARING]
list=*.lst
FFTdB=100
scope=8192
Max_trials=50
Min_sd=0.01
Response_time=1
Min_gap=1
Max_gap=1
limit=10
simulate=n
Task=Y/N
Random=n
MinFz=1000
MaxFz=9000
MinLev=-60
MaxLev=90
Protocol=1
Algo=ANSI
Freq_set=Wide
Freq_start=125
Freq_stop=11200
Per_octave=2
Level_start=40
Level_step=5
ramp=10

[PROBE]
rate=32000
size=8192
chk_swps=1
cal_skps=1
cal_swps=5
cal_skps=1
cal_sets=3
atten=30
calibrate=~bbn
FFTdB=60
FFTkHz=10
scope=8192
Niter=8000
Ext_Iter=N
Temp=25
Diacav=0.8
Max_len=12
Ncav=5
MinRes=1
debug=0
limit=100
lentst=6.0
f1_erf=500
f2_erf=8000

[TONE]
rate=32000
size=2048
frequency=1000
level=65
duration=2
repeated=1
channel=a
ramp=10
skips=2
refresh=5
