/* fk.h  - list of PC function key codes */

#define MFN		0x0400
#define LEFT_CLICK	(MFN | 1)
#define RIGHT_CLICK	(MFN | 2)

#define FN		0x0800
#define FK_Shift_Tab    (15|FN)
#define FK_Alt_M        (50|FN)
#define FK_F1           (59|FN)
#define FK_F2           (60|FN)
#define FK_F3           (61|FN)
#define FK_F4           (62|FN)
#define FK_F5           (63|FN)
#define FK_F6           (64|FN)
#define FK_F7           (65|FN)
#define FK_F8           (66|FN)
#define FK_F9           (67|FN)
#define FK_F10          (68|FN)
#define FK_F11          (69|FN)
#define FK_F12          (70|FN)
#define FK_Home         (71|FN)
#define FK_Up_Arrow     (72|FN)
#define FK_PgUp         (73|FN)
#define FK_Left_Arrow   (75|FN)
#define FK_Right_Arrow  (77|FN)
#define FK_End          (79|FN)
#define FK_Down_Arrow   (80|FN)
#define FK_PgDn         (81|FN)
#define FK_Ins          (82|FN)
#define FK_Del          (83|FN)
#define FK_Ctrl_Left    (115|FN)
#define FK_Ctrl_Right   (116|FN)
#define FK_Ctrl_End     (117|FN)
#define FK_Ctrl_PgDn    (118|FN)
#define FK_Ctrl_Home    (119|FN)
#define FK_Ctrl_PgUp    (132|FN)

#define Ctrl_C  	(3)
#define Ctrl_M  	(13)
#define Ctrl_P  	(16)
#define Ctrl_W  	(23)
#define Tab		(9)
#define Esc		(27)
